# Generated by Django 5.2.4 on 2025-08-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_remove_recipe_user_alter_recipe_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cooking_time_unit",
            field=models.CharField(
                choices=[("min", "Minutes"), ("hr", "Hours")],
                default="min",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveIntegerField(help_text="Time"),
        ),
    ]
